package com.barracudatrial.game.route;

import net.runelite.api.coords.WorldPoint;
import net.runelite.api.gameval.ObjectID;

import java.util.List;
import java.util.Set;

public class JubblyJiveConfig implements TrialConfig
{
	public static final WorldPoint TOAD_PICKUP_LOCATION = new WorldPoint(2245, 3009, 0); // ID: BALLOON_TOAD_PILE

	public static final int BOAT_EXCLUSION_WIDTH = 4;
	public static final int BOAT_EXCLUSION_HEIGHT = 8;

	public static final JubblyJiveToadPillar[] TOAD_PILLARS =
	{
		new JubblyJiveToadPillar(
				new WorldPoint(2264, 3003, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_0_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK0_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK0_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_0_PARENT, // 59124
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_0_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_0
		),
		new JubblyJiveToadPillar(
				new WorldPoint(2294, 2989, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_1_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK1_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK1_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_1_PARENT, // 59130
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_1_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_1
		),
		new JubblyJiveToadPillar(
				new WorldPoint(2309, 3011, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_2_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK2_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK2_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_2_PARENT, // 59136
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_2_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_2
		),
		new JubblyJiveToadPillar(
				new WorldPoint(2349, 3000, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_3_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK3_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK3_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_3_PARENT, // 59142
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_3_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_3
		),
		new JubblyJiveToadPillar(
				new WorldPoint(2375, 2955, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_4_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK4_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK4_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_4_PARENT, // 59148
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_4_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_4
		),
		new JubblyJiveToadPillar(
				new WorldPoint(2422, 2950, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_5_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK5_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK5_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_5_PARENT, // 59154
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_5_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_5
		),
		new JubblyJiveToadPillar(
				new WorldPoint(2422, 2998, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_6_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK6_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK6_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_6_PARENT, // 59160
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_6_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_6
		),
		new JubblyJiveToadPillar(
				new WorldPoint(2442, 3018, 0),
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_7_PARENT,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK7_NO_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_ROCK7_TOAD,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_7_PARENT, // 59166
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_7_NOOP,
				ObjectID.SAILING_BT_JUBBLY_JIVE_PILLAR_CLICKBOX_7
		)
	};

	private static final Set<Integer> SHIPMENT_IDS = Set.of(
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_1,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_2,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_3,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_4,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_5,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_6,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_7,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_8,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_9,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_10,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_11,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_12,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_13,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_14,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_15,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_16,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_17,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_18,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_19,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_20,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_21,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_22,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_23,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_24,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_25,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_26,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_27,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_28,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_29,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_30,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_31,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_32,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_33,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_34,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_35,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_36,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_37,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_38,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_39,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_40,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_41,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_42,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_43,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_44,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_45,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_46,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_47,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_48,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_49,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_50,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_51,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_52,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_53,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_54,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_55,
			ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_56
	);
	private static final int SHIPMENT_IMPOSTOR_ID = ObjectID.SAILING_BT_JUBBLY_JIVE_COLLECTABLE_SUPPLIES;

	// Same as Tempor - if Gwenith has the same rock ids we can remove this abstraction
	private static final Set<Integer> ROCK_IDS = Set.of(
		59314, 59315, 60437, 60438, 60440, 60441, 60442, 60443, 60444
	);

	private static final Set<Integer> SPEED_BOOST_IDS = Set.of(
		ObjectID.SAILING_RAPIDS_STRONG
	);

	public static final Set<Integer> FETID_POOL_IDS = Set.of(
		ObjectID.SAILING_FETID_POOL,
		ObjectID.SAILING_FETID_POOL_2X2,
		ObjectID.SAILING_FETID_POOL_3X3A,
		ObjectID.SAILING_FETID_POOL_3X3B,
		ObjectID.SAILING_FETID_POOL_3X3C
	);

	@Override
	public TrialType getTrialType()
	{
		return TrialType.JUBBLY_JIVE;
	}

	@Override
	public Set<Integer> getShipmentBaseIds()
	{
		return SHIPMENT_IDS;
	}

	@Override
	public int getShipmentImpostorId()
	{
		return SHIPMENT_IMPOSTOR_ID;
	}

	public WorldPoint getToadPickupLocation()
	{
		return TOAD_PICKUP_LOCATION;
	}

	@Override
	public Set<Integer> getRockIds()
	{
		return ROCK_IDS;
	}

	@Override
	public Set<Integer> getSpeedBoostIds()
	{
		return SPEED_BOOST_IDS;
	}

	@Override
	public List<RouteWaypoint> getRoute(Difficulty difficulty)
	{
		return JubblyJiveRoutes.getRoute(difficulty);
	}
}
